### PR TITLE
Update Benchmarking Kafka docs (#87)

### PR DESCRIPTION
**Pull request by panyuenlau**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| License         | Apache 2.0

### What's in this PR?

cherry-pick a028f85016bbe74344df16810f2a568b2973c041 into the master branch

### Why?

The steps are outdated

### Checklist

- [x] User guide and development docs updated (if needed)

### CODE REVIEW

**Comment by panyuenlau** [comment]
Question to the reviewers: not sure if want to remove/update the banzai-cli related stuff (I believe they are no longer valid), for example: https://github.com/banzaicloud/koperator-docs/blob/13da74b3f8c730d6e9979dc183bcf7cbc31bfe5b/docs/benchmarks/_index.md?plain=1#L8-L13

**Comment by fekete-robert** [comment]
We do want to remove it, I have an older PR for that (https://github.com/banzaicloud/koperator-docs/pull/78), but I didn't want to merge it into this PR, but we can do it. It might need some updates.

**Comment by panyuenlau** [comment]
> We do want to remove it, I have an older PR for that (#78), but I didn't want to merge it into this PR, but we can do it. It might need some updates.

Thanks @fekete-robert - wasn't aware of that, I'd say we can merge this one because I tested the actual steps, then we can resolve the conflicts for #78. What do you think?

**Comment by fekete-robert** [comment]
@panyuenlau Sure, let's do it that way

**Review by fekete-robert — APPROVED** [review]

**Review by Kuvesz — APPROVED** [review]

**Review by pregnor — APPROVED** [review]

**Pull request merged**
